### PR TITLE
Improved Readme.md . Changes aim to improve the formatting, clarify steps, and ensure consistency throughout your README

### PR DESCRIPTION
**Pull request by vinayaksoni1729**

### CODE REVIEW

**Comment by vinayaksoni1729** [comment]
Improved Readme.md . Changes aim to improve the formatting, clarify steps, and ensure consistency throughout your README

**Comment by vinayaksoni1729** [comment]
By default, Zero123++ generates opaque images with a gray background (the zero for Stable Diffusion VAE). You can run an extra background removal pass like rembg to remove the gray background:
# !pip install rembg
import rembg
result = rembg.remove(result)
result.show()

**Comment by eliphatfs** [comment]
Thanks, but you are removing the ControlNet, Citation and Running Demo Locally sections of the README. Also, as others have contributed to the README there are now conflicts. Could you please check these out?

**Comment by vinayaksoni1729** [comment]
@eliphatfs Fixed! check now!

**Comment by vinayaksoni1729** [comment]
@eliphatfs missed by mistake last time

**Comment by eliphatfs** [comment]
Github shows that the PR contains exactly same contents with the main branch and thus there is nothing to merge.
image

**Comment by vinayaksoni1729** [comment]
@eliphatfs sorry my bad actually I am working with so many codes so mixed up

**Comment by vinayaksoni1729** [comment]
Added How to Create a Virtual Environment

**Comment by vinayaksoni1729** [comment]
@eliphatfs check now if any issue

**Pull request closed without merging**
